"""initial

Revision ID: 4655d58fea6b
Revises: 
Create Date: 2023-12-05 00:30:47.742727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4655d58fea6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donation_requests_id', table_name='donation_requests')
    op.drop_table('donation_requests')
    op.add_column('donations', sa.Column('meet_up_location', sa.String(), nullable=True))
    op.add_column('donations', sa.Column('user_name', sa.String(), nullable=True))
    op.drop_column('donations', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('donations', 'user_name')
    op.drop_column('donations', 'meet_up_location')
    op.create_table('donation_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('donation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DONE', name='requeststatus'), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], name='donation_requests_donation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='donation_requests_pkey')
    )
    op.create_index('ix_donation_requests_id', 'donation_requests', ['id'], unique=False)
    # ### end Alembic commands ###
